<x-dashboard>
    @php($company = Auth::user()->company)
    @php($projects = $company?->projects ?? collect())
    @php($talents = $company?->talents ?? collect())
    <div class="flex flex-col gap-7">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="m-0 text-sm font-medium text-sky-600">Overview</p><h1 class="mb-0 mt-1 text-3xl font-bold tracking-tight">{{ __('admin/dashboard.dashboard') }}</h1><p class="mb-0 mt-2 text-sm text-slate-500">A clear view of your hiring workspace.</p></div><a href="{{ route('job-listing') }}" class="inline-flex h-10 items-center justify-center rounded-md bg-sky-600 px-4 text-sm font-medium text-white no-underline shadow-sm hover:bg-sky-700">View job listings</a></div>
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="m-0 text-sm font-medium text-slate-500">{{ __('admin/dashboard.new_candidates_to_review') }}</p><p class="mb-0 mt-3 text-3xl font-bold">{{ \App\Models\Talent::where('created_at', '>=', today()->subDays(7))->count() }}</p><a href="{{ route('job-applicants') }}" class="mt-3 inline-block text-sm font-medium text-sky-600 no-underline">Review candidates →</a></div>
            <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="m-0 text-sm font-medium text-slate-500">{{ __('admin/dashboard.job_openings') }}</p><p class="mb-0 mt-3 text-3xl font-bold">{{ $projects->count() }}</p><p class="mb-0 mt-3 text-sm text-slate-500">Active roles in your workspace</p></div>
            <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="m-0 text-sm font-medium text-slate-500">{{ __('admin/dashboard.applicants') }}</p><p class="mb-0 mt-3 text-3xl font-bold">{{ $talents->count() }}</p><p class="mb-0 mt-3 text-sm text-slate-500">Registered candidates</p></div>
            <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="m-0 text-sm font-medium text-slate-500">{{ __('admin/dashboard.message_received') }}</p><p class="mb-0 mt-3 text-3xl font-bold">{{ Auth::user()->unreadNotifications->count() }}</p><a href="{{ route('messages') }}" class="mt-3 inline-block text-sm font-medium text-sky-600 no-underline">Open inbox →</a></div>
        </div>
        <div class="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(18rem,.9fr)]">
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="m-0 text-lg font-semibold">{{ __('admin/dashboard.job_statistics') }}</h2><p class="mb-0 mt-1 text-sm text-slate-500">{{ __('admin/dashboard.showing_job_statistics') }}</p></div><div class="flex rounded-lg bg-slate-100 p-1"><button class="chart-period rounded-md bg-white px-3 py-1.5 text-sm font-medium shadow-sm" data-period="week">{{ __('admin/dashboard.week') }}</button><button class="chart-period rounded-md px-3 py-1.5 text-sm font-medium text-slate-600" data-period="month">{{ __('admin/dashboard.month') }}</button><button class="chart-period rounded-md px-3 py-1.5 text-sm font-medium text-slate-600" data-period="year">{{ __('admin/dashboard.year') }}</button></div></div><div class="mt-6 h-72"><canvas id="chartCanvas"></canvas></div></section>
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex items-center justify-between"><h2 class="m-0 text-lg font-semibold">Recent candidates</h2><a href="{{ route('job-applicants') }}" class="text-sm font-medium text-sky-600 no-underline">View all</a></div><div class="mt-5 space-y-4">@forelse($talents->sortByDesc('created_at')->take(5) as $talent)<div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-full bg-sky-100 text-sm font-semibold text-sky-700">{{ str($talent->user?->name ?? '?')->substr(0, 1)->upper() }}</span><div class="min-w-0 flex-1"><p class="m-0 truncate text-sm font-medium text-slate-800">{{ $talent->user?->name ?? 'Unknown candidate' }}</p><p class="mb-0 mt-0.5 text-xs text-slate-500">Added {{ $talent->created_at?->diffForHumans() }}</p></div></div>@empty<p class="text-sm text-slate-500">No candidates yet.</p>@endforelse</div></section>
        </div>
    </div>
    @push('scripts')<script>let chart;function loadChartData(period){axios.get(`/project-chart/${period}`).then(({data})=>updateChart(data.labels,data.data));}function updateChart(labels,data){const ctx=document.getElementById('chartCanvas').getContext('2d');if(chart){chart.data.labels=labels;chart.data.datasets[0].data=data;chart.update();return;}chart=new Chart(ctx,{type:'bar',data:{labels,datasets:[{label:'Projects published',data,backgroundColor:'rgba(2,132,199,.2)',borderColor:'rgb(2,132,199)',borderWidth:1,borderRadius:6}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#e2e8f0'}},x:{grid:{display:false}}}}});}document.addEventListener('DOMContentLoaded',()=>{loadChartData('week');document.querySelectorAll('.chart-period').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.chart-period').forEach(item=>item.className='chart-period rounded-md px-3 py-1.5 text-sm font-medium text-slate-600');button.className='chart-period rounded-md bg-white px-3 py-1.5 text-sm font-medium shadow-sm';loadChartData(button.dataset.period);}));});</script>@endpush
</x-dashboard>
